### ISSUE TITLE
Does not work when branch name contains a '/'

### ISSUE THREAD

**Issue by Mukundan314** [dolphingarlic/git-the-lines#16]
url tested with: https://gitlab.com/Mukundan314/test/-/blob/test/test/test.txt#L2

**Comment by Mukundan314** [comment]
same problem on GitHub too url tested with: https://github.com/cheran-senthil/PyRival/blob/feat/lazy-segment-tree-custom-add/pyrival/algebra/chinese_remainder.py#L16

**Comment by dolphingarlic** [comment]
Do you know how many `/`s a branch name can have? The easiest solution I have in mind would just be to try all branch/file-path pairs, but that's quite inefficient. (I don't think there's a simple regex solution :frowning:)

**Comment by Mukundan314** [comment]
I think we currently have three options

 ### First Option: List branches of the repo

API to do this on GitHub: https://docs.github.com/en/rest/reference/repos#list-branches
API to do this on GitLab: https://docs.gitlab.com/ee/api/branches.html

### Second Option: Manually construct raw url

In GitHub raw urls are of the form: `https://raw.githubusercontent.com/<repo>/<ref>/<file_path>`
In GitLab raw urls are of the form: `https://gitlab.com/<repo>/-/raw/r<ref>/<file_path>`

Since here `ref` and `file_path` are side-by-side we don't need to separate them in the regex.

**Note:** It will be hard to support private repos with this method

### Third Option: Trying all branch/file-path pairs

Like you said this option is quite inefficient

---

IMO the first option is probably the most elegant I can create PR for the first option if you want.

**Comment by dolphingarlic** [comment]
It would be really great if you create a PR :smiley: 

Could you maybe also add a test for this case?
