### ISSUE TITLE
Extrapolate and post filename and line of the snippet. 

### ISSUE THREAD

**Issue by Al12rs** [dolphingarlic/git-the-lines#31]
Thanks for the nice bot, it helps when using discord as the main development discussion platform.

I wanted to propose the addition of the filename and displayed lines in the bot message, in a more readable way than what is contained in the link. 

For example here
![image](https://user-images.githubusercontent.com/26797547/98144280-7def6480-1eca-11eb-86a7-4129f2d4b164.png)
the bot doesn't currently give any context of where the lines are from and the users need to extrapolate it from the link, which makes it more difficult at a glance.

In comparison this is how github renders the link: 

https://github.com/dolphingarlic/git-the-lines/blob/1a4475c3cc2ae976d3f8a75ed7dbeb4854ebc2d5/cogs/utils.py#L7-L14

Regarding how to show the information, I was thinking of something simple like this:
![image](https://user-images.githubusercontent.com/26797547/98145837-6ebce680-1ecb-11eb-98c6-884d3871a316.png)
 
Where the filename is in bold and the line number/numbers are in normal text.

I work on an opensource project with a pretty sizable codebase and being able to see at a glance which file is being snipped would be very helpful. 
In my opinion the repository name isn't necessary since it's usually clear from the context or from the filename itself. In case it's needed the developer can still get the info from the link, although less conveniently. Also adding that would risk in my opinion cluttering the extracted information too much, reducing it's readability at a glance.

**Comment by dolphingarlic** [comment]
Thanks for the suggestion! I've implemented this feature in https://github.com/dolphingarlic/git-the-lines/commit/c1eab890d162e1235cc50a239d876ad8665dc04b. Let me know if anything breaks because of this

**Comment by Al12rs** [comment]
Nice, looks clean! Thank you very much!
