### ISSUE TITLE
Too many embeds

### ISSUE THREAD

**Issue by Al12rs** [dolphingarlic/git-the-lines#33]
Hey, it's me again. 

After a few weeks of using the bot on our development server the other developers asked me to kick it since there were too many embeds for all kinds of links. 

The general consensus was that the line quoting feature is useful, while the other embeds like gists, commits and PR embeds are annoying and cumbersome. They might offer some info, but usually these links are posted to be clicked on in the first place so the embed isn't really that useful, they take too much space for what they offer ad interrupt the flow of the conversation with big bulky info.

So basically the feedback is that the line quoting feature is neat but all the other embeds make it annoying enough for people to not want it on the server.

If you remove those things and just keep the core feature of quoting lines I would be very happy so we can keep the bot, but I can understand if you don't want to cut features you have worked on. 

I personally feel they would be good as optional additions, but since the bot doesn't have a database, you either get all the features or nothing, so in this case I would gravitate towards making the bot only do one thing well.

Let me know what you think

**Comment by dolphingarlic** [comment]
Hi, thanks for the feedback. I've disabled the embeds for commits and PRs. I didn't mind, since they were experimental and a result of Hacktoberfest anyway :P

Also, does the regex work fine in general? I've only tested it on a few repos before.

**Comment by Al12rs** [comment]
Ok I've re-enabled the bot. Thanks!
In my experience the regex seamd to always work when we expected it.

Well as I say that I notice that PR code diff Line links don't work.

The links are these and they have a different format than the normal line links. They use R and L to indicate whether they mean the left or right version:

https://github.com/dolphingarlic/git-the-lines/commit/b6fb32e19a60176a951a099e919eb7650cf5eb74#diff-36f6200cd8353111badb874140eba3af6055f4cc5839fbdeb9ede992620828c1R40

https://github.com/dolphingarlic/git-the-lines/commit/b6fb32e19a60176a951a099e919eb7650cf5eb74#diff-36f6200cd8353111badb874140eba3af6055f4cc5839fbdeb9ede992620828c1L40

If you want to support these as well I would only report one of the two lines of the diff, or the embed would become a mess.

I don't think these are too common since we usually use PR code comments instead of discussing on discord in these cases.
