### ISSUE TITLE
Unwanted quoting when links are followed by comma

### ISSUE THREAD

**Issue by Al12rs** [dolphingarlic/git-the-lines#34]
We found this instance where posting a link to a file followed by a comma `,` it would quote line 1 of the file which is probably not what the user wanted:
eg:  `https://github.com/ModOrganizer2/modorganizer/blob/master/src/mainwindow.ui,`

![image](https://user-images.githubusercontent.com/26797547/102833606-da163580-43f1-11eb-8f4c-24847bba0d79.png)

**Comment by dolphingarlic** [comment]
Fixed with https://github.com/dolphingarlic/git-the-lines/commit/99ed3a234d9ce0c54addfdf1dd905c180b7a797f
