### ISSUE TITLE
Disable embedded link images/metadata

### ISSUE THREAD

**Issue by onedr0p** [dolphingarlic/git-the-lines#39]
Current result:

![image](https://user-images.githubusercontent.com/213795/117542303-1daabe00-afe6-11eb-99a5-b9df0cd1d143.png)

Expected result:

![image](https://user-images.githubusercontent.com/213795/117542364-4fbc2000-afe6-11eb-979e-dd33350e209a.png)

It would be nice if the bot could not post the GitHub cards, or any other metadata. Just print the lines.

**Comment by dolphingarlic** [comment]
It already doesn't post the card or metadata. The card is from discord itself

**Comment by onedr0p** [comment]
I can see the other bot [Github lines](https://github.com/diogoscf/github-lines) does what I am requesting here. It removes the metadata for us.

![image](https://user-images.githubusercontent.com/213795/117553584-6bdcb300-b020-11eb-9a59-5360c09fbb5a.png)

If you choose not to support it, that's okay with me. I just find it odd you closed the issue, is there somewhere else we should make feature requests?
