### ISSUE TITLE
Clear Git the Lines using reactions

### ISSUE THREAD

**Issue by onedr0p** [dolphingarlic/git-the-lines#40]
I see this PR but I am not seeing the X being added to the Git the lines post

https://github.com/dolphingarlic/git-the-lines/issues/19

**Comment by onedr0p** [comment]
Current:

![image](https://user-images.githubusercontent.com/213795/117542566-294ab480-afe7-11eb-8d99-bd453edabb5e.png)

Expected:

![image](https://user-images.githubusercontent.com/213795/117542582-3667a380-afe7-11eb-8849-97bf4b779603.png)

When I click the X it should delete the "Git the lines" message

**Comment by dolphingarlic** [comment]
This already happens when you send a message. The reaction just disappears after 10 seconds

**Comment by onedr0p** [comment]
That is not true, I do not see the reaction.

**Comment by dolphingarlic** [comment]
![image](https://user-images.githubusercontent.com/31325319/117552528-2f26b100-b04c-11eb-9c0d-07c394c59649.png)

I think the bot needs permission to add reacts to do this though

**Comment by onedr0p** [comment]
I'll try to reconnect the bot with those permissions, thanks.

**Comment by onedr0p** [comment]
Hm.. I removed the bot and added it back. I made sure reactions permission was enabled. I still do not see this behavior.
